sudo: false
language: ruby
rvm:
  - 2.1.0 # target version (requires old nio4r 1.9.x)
  - 2.2.2 # Minimum for latest nio4r
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - cat Gemfile.lock
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  