language: ruby
rvm:
- 2.4.3
- 2.5.1
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ip a
- cat /etc/hosts
after_script:
- cat Gemfile.lock
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: rubygems
  api_key:
    secure: TcdJ+iGasCJJFqG9BqWBwsZrKKMTbvWJ+CNMeSYLLCuFOSW74m/A0DBkVddgaADlY1EYIkNkAAaFEaPgQsPunsll8wvAwbddXX5LOsrUaIk3gaYk3V8sudnn437HGsFIvMVQ8yg8fc25p2MMz/pCVPyb1JcMfRBHVDB4I39LUHthi24aGJJn2EZPgiarXYFbsiO/aMId22/Yxw32gG3+ULd2GAhxQ55zZzxfTzvwRian3U9kY4uO79a3rjKH9beSGXYfH3hecp0NEt65vEjwUnfohx7M4We9SHYLm3bEpPtLjUrI2eaaMbeY9bp3UkwVetsL3Ms4METU49sVbYwDrjt+H5s7GvSKdZt/ybmgJWu/Z7llUVrZzJLXRIpMTEGOYh2l+pgzOon+0fmKkcjSbveM6BCiQbMkt+kHHEGlm01VrZPlBeuhnl0ORAxTvAb9PZjs5/myrMrd7C+MAFp9xT+kJ3BodnhV8oPP8imHLqZiu3eAQBk6YtjEOJ3VPlk4VZzL2risXWdKpOeTXU/5WAJJLJmUWNFtfWDsd+EkxprTpNHzymNGUxR2m3OVdqlEwUELCggrkaSNVrYgBFVkrPz0Th23ALsd5YbN16p5eRVbozJP35SxHWQzmCj8Ye7vRgeIN9AyT6FSmuNTbJuPFFGPQaFDmpFkH/CreOXJFNU=
  gem: nio4r-websocket
  on:
    tags: true
    rvm: 2.4.3
notifications:
  slack:
    secure: lV6b8Gh1E4XLWdEMdfa9PB+eZvLJwaAH8GC3+wdv6fYCWGBgEKX6kF8swYmzIj+vwPpXMKWnOX2l90l1Sn4jcljfG9gaFp5To8sBYxCieSg5Y8DoRHfohL1YU0It1kJN83LPTjGsp1sNkylHH8s222jdMF1Jekq6MkqxHH+EFGIw0Q+KQB8Vi6K6tDGkR30v2luew/1klVRWGD28dDVrA7E6oejHuUU0YWj/XhIJNORhvRGDPL5q9dkq2W4QJuLOls4arU7W6koLGtOgKMK1/x9RS62NdBxdNvRWGyGg3v2ErlWtTJWEbED6q8WRYXO4TN7PrZgVhY/kcPiGwzwKDGk2Hej9UvWTeW1HjN5yVFeU7D6fH3WC+Ys6gwp1yBkf90xWYpH7YQ4UaodSRdPjXU7WFnfmaFlnlkvvO13igRJa+1cRM7hdtrN7d3/3CDJdnE+YOqa1oSF+3gLcCu837Zgn2dc5colDRbnyVlDbjVVIkPFNxwZ9/ixg97m5VwVd8+PvqaFvIuNpPu9tflxguyAzYN5uhlLOu5pW8syWDE1fpzVLZ33LsWGAhZ/X3Ups+KxsPC46sqdIV54ikW7V5kpEjFlutfed1aWYxkdjMz90HCcQSEQ3YrJOluOyFa28px2lnA0Bdp2eVLkPDGn2W+9U6d1K/zGpgejb6aiADBY=
